<?php

namespace App\Console\Commands;

use App\Models\Lead;
use App\Models\Organization;
use App\Models\OrganizationMembership;
use Illuminate\Console\Command;

class SeedDemoLeads extends Command
{
    protected $signature = 'leads:seed-demo {organization? : Organization public ID} {--count=10 : Number of demo leads to add (1-100)}';

    protected $description = 'Add clearly labelled demo leads to an existing organization without deleting any data';

    public function handle(): int
    {
        $organization = filled($this->argument('organization'))
            ? Organization::query()->where('public_id', $this->argument('organization'))->first()
            : Organization::query()->orderBy('id')->first();

        if ($organization === null) {
            $this->error('No organization was found. Create an organization first or pass its public ID.');

            return self::FAILURE;
        }

        $count = (int) $this->option('count');
        if ($count < 1 || $count > 100) {
            $this->error('The --count value must be between 1 and 100.');

            return self::FAILURE;
        }

        $ownerId = OrganizationMembership::query()
            ->where('organization_id', $organization->id)
            ->orderBy('id')
            ->value('user_id');
        $names = [
            'Amina Bello', 'Tunde Okafor', 'Chiamaka Eze', 'Ibrahim Musa', 'Zainab Yusuf',
            'Femi Adeyemi', 'Adaobi Nwosu', 'David Olatunji', 'Blessing James', 'Samuel Danladi',
        ];
        $companies = [
            'BrightPath Services', 'Northstar Retail', 'Kora Logistics', 'Beacon Health', 'Summit Foods',
            'Westfield Energy', 'Cedar Homes', 'Orbit Learning', 'Harbour Trade', 'Prime Field Group',
        ];
        $statuses = ['new', 'contacted', 'qualified', 'new', 'contacted', 'qualified', 'won', 'new', 'lost', 'contacted'];

        for ($index = 0; $index < $count; $index++) {
            $name = $names[$index % count($names)];
            Lead::query()->create([
                'organization_id' => $organization->id,
                'assigned_user_id' => $ownerId,
                'created_by_user_id' => $ownerId,
                'name' => $name.' (Demo)',
                'company' => $companies[$index % count($companies)],
                'email' => 'demo.lead.'.($index + 1).'@example.test',
                'phone' => '+234 800 000 '.str_pad((string) ($index + 1), 4, '0', STR_PAD_LEFT),
                'status' => $statuses[$index % count($statuses)],
                'value' => 50000 + ($index * 25000),
                'notes' => 'Demo lead generated by leads:seed-demo. Safe to edit or delete.',
                'follow_up_at' => now()->addDays($index + 1)->setTime(10, 0),
            ]);
        }

        $this->info("Added {$count} demo lead(s) to {$organization->name} ({$organization->public_id}).");

        return self::SUCCESS;
    }
}
