[rtpengine]
table = 0

interface = 213.199.52.39
ice-lite = false
ice-host = 213.199.52.39

listen-ng = 127.0.0.1:2223
listen-http = 127.0.0.1:2225
listen-cli = 127.0.0.1:2224

timeout = 60
silent-timeout = 3600
final-timeout = 10800

tos = 184

dtls-passive = true

foreground = false
pidfile = /run/rtpengine/rtpengine-daemon.pid
num-threads = 4

port-min = 30000
port-max = 40000

recording-dir = /var/spool/rtpengine
recording-method = proc

log-level = 6
log-stderr = false
log-facility = local0

kernel-table = no
